CREATE TABLE USER (
	ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) UNIQUE, 
	pwd VARCHAR(255),
	salt VARCHAR(255)
);

CREATE TABLE TEXT (
	ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255),
	content LONGVARCHAR,
	projectID INTEGER
);

CREATE TABLE PROJECTS (
	ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	name VARCHAR(255), 
	description LONGVARCHAR, 
	ownerID NUMERIC
);

-- OK we need this table for the SecLab
-- We know that all the passwords and userdata are in this file
-- But THIS file IS NOT part of the lesson

-- Usingthe following passwords is like cheating in a game.....
--

/***
 *                                        __          ____                                     __
 *     /'\_/`\                 __        /\ \        /\  _`\                                __/\ \__
 *    /\      \  __  __   ___ /\_\    ___\ \ \___    \ \,\L\_\     __    ___  __  __  _ __ /\_\ \ ,_\  __  __
 *    \ \ \__\ \/\ \/\ \/' _ `\/\ \  /'___\ \  _ `\   \/_\__ \   /'__`\ /'___\\ \/\ \/\`'__\/\ \ \ \/ /\ \/\ \
 *     \ \ \_/\ \ \ \_\ \\ \/\ \ \ \/\ \__/\ \ \ \ \    /\ \L\ \/\  __//\ \__/ \ \_\ \ \ \/ \ \ \ \ \_\ \ \_\ \
 *      \ \_\\ \_\ \____/ \_\ \_\ \_\ \____\\ \_\ \_\   \ `\____\ \____\ \____\ \____/\ \_\  \ \_\ \__\\/`____ \
 *       \/_/ \/_/\/___/ \/_/\/_/\/_/\/____/ \/_/\/_/    \/_____/\/____/\/____/\/___/  \/_/   \/_/\/__/ `/___/> \
 *                                                                                                         /\___/
 *                                                                                                         \/__/
 *
 *     ____                                               __          ____
 *    /\  _`\                                            /\ \        /\  _`\
 *    \ \ \L\ \     __    ____    __     __     _ __  ___\ \ \___    \ \ \L\_\  _ __  ___   __  __  _____
 *     \ \ ,  /   /'__`\ /',__\ /'__`\ /'__`\  /\`'__\'___\ \  _ `\   \ \ \L_L /\`'__\ __`\/\ \/\ \/\ '__`\
 *      \ \ \\ \ /\  __//\__, `\\  __//\ \L\.\_\ \ \/\ \__/\ \ \ \ \   \ \ \/, \ \ \/\ \L\ \ \ \_\ \ \ \L\ \
 *       \ \_\ \_\ \____\/\____/ \____\ \__/.\_\\ \_\ \____\\ \_\ \_\   \ \____/\ \_\ \____/\ \____/\ \ ,__/
 *        \/_/\/ /\/____/\/___/ \/____/\/__/\/_/ \/_/\/____/ \/_/\/_/    \/___/  \/_/\/___/  \/___/  \ \ \/
 *                                                                                                    \ \_\
 *                                                                                                     \/_/
 */
